### ISSUE TITLE
Test failure: HelloWorld

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/ServerTests#141] opened 2018-08-15 20:01 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=531775&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) occasionally with the following error:
```
System.InvalidOperationException : Failed to start nginx
   at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.SetupNginx(String redirectUri, Uri originalUri)
   at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.DeployAsync()
   at ServerComparison.FunctionalTests.HelloWorldTests.HelloWorld(TestVariant variant) in /_/test/ServerComparison.FunctionalTests/HelloWorldTest.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test HelloWorld-Server: Nginx, TFM: netcoreapp2.2, Type: Standalone, Arch: x64 at 2018-08-15T18:23:09
| [0.003s] TestLifetime Information: Starting test HelloWorld_Nginx_netcoreapp2.2_x64_Standalone at 2018-08-15T18:23:09
| [0.018s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: Executing command dotnet publish  --output "/mnt/temp/buildTmp/1d343f604e7a47c4b13f367beb67f3c3" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false --runtime linux-x64 
| [1.110s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: host process ID 75998 shut down
| [1.112s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Host process shutting down.
| [0.337s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
| [0.338s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [2.541s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet-publish stdout:   ServerComparison.TestSites -> /mnt/work/33bdfc1cae7b2a38/modules/ServerTests/test/ServerComparison.TestSites/bin/Release/netcoreapp2.2/linux-x64/ServerComparison.TestSites.dll
| [3.873s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet-publish stdout:   ServerComparison.TestSites -> /mnt/temp/buildTmp/1d343f604e7a47c4b13f367beb67f3c3/
| [3.930s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: dotnet publish finished with exit code : 0
| [3.930s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: Executing /mnt/temp/buildTmp/1d343f604e7a47c4b13f367beb67f3c3/ServerComparison.TestSites  --urls http://localhost:38518/ --server Microsoft.AspNetCore.Server.Kestrel
| [3.930s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [3.931s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [3.935s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: Started /mnt/temp/buildTmp/1d343f604e7a47c4b13f367beb67f3c3/ServerComparison.TestSites. Process Id : 76078
| [4.381s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: /mnt/temp/buildTmp/1d343f604e7a47c4b13f367beb67f3c3/ServerComparison.TestSites stdout: Hosting environment: Production
| [4.382s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: /mnt/temp/buildTmp/1d343f604e7a47c4b13f367beb67f3c3/ServerComparison.TestSites stdout: Content root path: /mnt/temp/buildTmp/1d343f604e7a47c4b13f367beb67f3c3/
| [4.383s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: /mnt/temp/buildTmp/1d343f604e7a47c4b13f367beb67f3c3/ServerComparison.TestSites stdout: Now listening on: http://localhost:38518
| [4.383s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Information: /mnt/temp/buildTmp/1d343f604e7a47c4b13f367beb67f3c3/ServerComparison.TestSites stdout: Application started. Press Ctrl+C to shut down.
| [4.403s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
| [4.408s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [4.408s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [4.408s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [4.409s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [4.908s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [4.908s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [4.909s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [4.909s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [5.408s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [5.409s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 failed (98: Address already in use)
| [5.409s] Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer Warning: nginx start stderr: nginx: [emerg] bind() to 0.0.0.0:44194 
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-08-15 20:01
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-08-16 01:00
ResponseCompression_NoCompression [failed with about the same error](http://aspnetci/viewLog.html?buildId=532093&buildTypeId=XPlat_Windows_Win8_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-08-17 00:02
ResponseCompression_AppCompression [failed with about the same error](http://aspnetci/viewLog.html?buildId=533284&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-08-18 00:01
ResponseCompression_NoCompression [failed with about the same error](http://aspnetci/viewLog.html?buildId=534200&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-26 00:10
HelloWorld [failed with about the same error](http://aspnetci/viewLog.html?buildId=539259&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-27 21:04
HelloWorld [failed with about the same error](http://aspnetci/viewLog.html?buildId=539853&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment] 2018-08-30 17:45
@Tratcher could you take a look? It looks like this is an ongoing failure (unlike other failures in this repo.)

**Comment by Tratcher** [comment] 2018-08-30 18:30
8/27 - ANCM v1 out of proc. GET request. Kestrel responds with a 408 Request Timeout after 1.9 seconds. The only possible source is here: https://github.com/aspnet/KestrelHttpServer/blob/cd6de2fa187b247e552954ae62df03a0b2198f87/src/Kestrel.Core/Internal/Http/Http1Connection.cs#L480-L485

But a headers timeout doesn't make any sense, the default timeout is 30 seconds. And why would ANCM time out sending the headers to Kestrel at all?

@pakrym @halter73 am I missing something? This error doesn't make much sense.

**Comment by halter73** [comment] 2018-08-30 19:05
> But a headers timeout doesn't make any sense, the default timeout is 30 seconds.

There was a regression while you were gone. The issue: #2850 The PR: #2851 It should fix should have propagated everywhere by now.

**Comment by Tratcher** [comment] 2018-08-30 19:07
Ah, that would do it. Closing this as resolved then.

**Closed by Tratcher** 2018-08-30 19:07 UTC
Labels: Branch:2.2, Branch:master, test-failure
